"""
v0.6.0 卡牌原型数据（65个原型 → 365张卡牌）

阵营机制主题:
  HEALTH: 治疗、护盾、奇迹（信仰阈值）
  LOVE: 偷取、控制、重定向、链接
  CAREER: 连击、成长、力量增幅
  FAMILY: 召唤、血统（死亡触发）、协同
  WEALTH: 资源生成、风险回报、金币倍增

稀有度分布（每阵营73张）:
  IRON: 37张 | BRONZE: 18张 | SILVER: 9张 | GOLD: 6张 | BLACK_GOLD: 3张
  原型数:   5        3              2               2              1

卡牌类型: UNIT(单位) / SPELL(法术) / ITEM(装备) / RELIC(遗物)
"""

ARCHETYPES = {
    # ============================================================
    # HEALTH 阵营 — 治疗、护盾、奇迹
    # ============================================================
    "HEALTH": [
        {
            "archetype_id": "HEALTH_IRON_HEALER",
            "faction": "HEALTH",
            "rarity": "IRON",
            "card_type": "UNIT",
            "name_templates": ["仁心{name}", "治愈者{name}", "医者{name}", "康复{name}", "护士{name}", "药师{name}", "杏林{name}", "白衣{name}"],
            "base_cost": 2,
            "base_stats": {"attack": 1, "health": 4},
            "base_effects": [{"type": "heal", "target": "self", "value": 2}],
            "lore_template": "{name}心怀善念，以仁术治愈世间疾苦。",
            "tags": ["heal", "faith"],
        },
        {
            "archetype_id": "HEALTH_IRON_SHIELD",
            "faction": "HEALTH",
            "rarity": "IRON",
            "card_type": "UNIT",
            "name_templates": ["护佑{name}", "坚盾{name}", "守卫者{name}", "庇护{name}", "铁壁{name}", "屏障{name}", "护法{name}"],
            "base_cost": 3,
            "base_stats": {"attack": 0, "health": 6},
            "base_effects": [{"type": "shield", "target": "all_allies", "value": 1}],
            "lore_template": "{name}以信仰为盾，守护同伴免于伤害。",
            "tags": ["shield", "defense"],
        },
        {
            "archetype_id": "HEALTH_IRON_MENDER",
            "faction": "HEALTH",
            "rarity": "IRON",
            "card_type": "SPELL",
            "name_templates": ["治愈之光", "恢复祷言", "甘泉{name}", "生命之水", "愈疗波", "安魂曲", "回春术", "再生"],
            "base_cost": 1,
            "base_stats": None,
            "base_effects": [{"type": "heal", "target": "target_ally", "value": 4}],
            "lore_template": "神圣的光芒洒落，伤痛在温暖中消散。",
            "tags": ["heal", "spell"],
        },
        {
            "archetype_id": "HEALTH_IRON_FAITH",
            "faction": "HEALTH",
            "rarity": "IRON",
            "card_type": "ITEM",
            "name_templates": ["圣徽", "祈祷念珠", "治愈护符", "光明十字架", "圣水瓶", "祝福之环", "信德之章"],
            "base_cost": 1,
            "base_stats": None,
            "base_effects": [{"type": "heal", "target": "self", "value": 1, "condition": "on_turn_start"}],
            "lore_template": "蕴含虔诚信念的圣物，佩戴者沐浴神恩。",
            "tags": ["heal", "item", "passive"],
        },
        {
            "archetype_id": "HEALTH_IRON_VITALITY",
            "faction": "HEALTH",
            "rarity": "IRON",
            "card_type": "SPELL",
            "name_templates": ["生命恩赐", "活力祝福", "强健体魄", "复苏之风", "元气满满", "生机勃勃", "血气方刚"],
            "base_cost": 2,
            "base_stats": None,
            "base_effects": [{"type": "buff", "target": "target_ally", "value": 2, "subtype": "health"}],
            "lore_template": "一股蓬勃的生命力涌入体内，身躯愈发强壮。",
            "tags": ["buff", "health"],
        },
        # BRONZE
        {
            "archetype_id": "HEALTH_BRONZE_PALADIN",
            "faction": "HEALTH",
            "rarity": "BRONZE",
            "card_type": "UNIT",
            "name_templates": ["圣骑{name}", "光明骑士{name}", "神佑战士{name}", "虔信{name}", "圣武士{name}", "光辉{name}"],
            "base_cost": 3,
            "base_stats": {"attack": 2, "health": 5},
            "base_effects": [
                {"type": "heal", "target": "self", "value": 2, "condition": "on_attack"},
                {"type": "shield", "target": "self", "value": 1, "condition": "on_damaged"},
            ],
            "lore_template": "{name}手持圣光之剑，以信仰之力治愈伤痕。",
            "tags": ["heal", "shield", "unit"],
        },
        {
            "archetype_id": "HEALTH_BRONZE_SANCTUARY",
            "faction": "HEALTH",
            "rarity": "BRONZE",
            "card_type": "SPELL",
            "name_templates": ["圣所结界", "治愈领域", "庇护之地", "安息所", "净化圣域", "疗愈法阵"],
            "base_cost": 4,
            "base_stats": None,
            "base_effects": [
                {"type": "heal", "target": "all_allies", "value": 2},
                {"type": "shield", "target": "all_allies", "value": 1},
            ],
            "lore_template": "神圣领域展开，所有友方沐浴在治愈之光中。",
            "tags": ["heal", "shield", "aoe"],
        },
        {
            "archetype_id": "HEALTH_BRONZE_MIRACLE",
            "faction": "HEALTH",
            "rarity": "BRONZE",
            "card_type": "RELIC",
            "name_templates": ["奇迹圣杯", "复活之羽", "不死鸟之泪", "重生十字章", "恩典之环", "天使羽衣"],
            "base_cost": 5,
            "base_stats": None,
            "base_effects": [
                {"type": "heal", "target": "all_allies", "value": 3, "condition": "on_death_ally"},
                {"type": "revive", "target": "random_ally", "value": 1, "condition": "faith_threshold_5"},
            ],
            "lore_template": "传说中的圣物，能在绝境中带来奇迹般的转机。",
            "tags": ["miracle", "heal", "revive", "relic"],
        },
        # SILVER
        {
            "archetype_id": "HEALTH_SILVER_ARCHANGEL",
            "faction": "HEALTH",
            "rarity": "SILVER",
            "card_type": "UNIT",
            "name_templates": ["大天使{name}", "炽天使{name}", "圣光天使{name}", "智天使{name}"],
            "base_cost": 5,
            "base_stats": {"attack": 3, "health": 6},
            "base_effects": [
                {"type": "heal", "target": "all_allies", "value": 2, "condition": "on_summon"},
                {"type": "heal", "target": "all_allies", "value": 1, "condition": "on_turn_start"},
            ],
            "lore_template": "{name}展开六翼，圣光普照大地，万物复苏。",
            "tags": ["heal", "aoe", "angel"],
        },
        {
            "archetype_id": "HEALTH_SILVER_HOLY",
            "faction": "HEALTH",
            "rarity": "SILVER",
            "card_type": "SPELL",
            "name_templates": ["神圣审判", "天罚之光", "净化烈焰", "驱魔圣言"],
            "base_cost": 4,
            "base_stats": None,
            "base_effects": [
                {"type": "damage", "target": "all_enemies", "value": 2},
                {"type": "heal", "target": "all_allies", "value": 3},
            ],
            "lore_template": "神圣之力化为光柱，惩戒邪恶的同时治愈信徒。",
            "tags": ["damage", "heal", "aoe"],
        },
        # GOLD
        {
            "archetype_id": "HEALTH_GOLD_SERAPH",
            "faction": "HEALTH",
            "rarity": "GOLD",
            "card_type": "UNIT",
            "name_templates": ["炽爱天使{name}", "光辉之翼{name}", "圣歌{name}"],
            "base_cost": 6,
            "base_stats": {"attack": 4, "health": 8},
            "base_effects": [
                {"type": "heal", "target": "all_allies", "value": 3, "condition": "on_turn_end"},
                {"type": "shield", "target": "all_allies", "value": 2, "condition": "on_summon"},
                {"type": "revive", "target": "random_ally", "value": 1, "condition": "on_death"},
            ],
            "lore_template": "{name}的歌声穿透天际，死亡亦无法阻挡她的恩典。",
            "tags": ["heal", "shield", "revive", "angel", "legendary"],
        },
        {
            "archetype_id": "HEALTH_GOLD_FOUNTAIN",
            "faction": "HEALTH",
            "rarity": "GOLD",
            "card_type": "RELIC",
            "name_templates": ["生命之泉", "永恒圣泉", "青春之泉"],
            "base_cost": 4,
            "base_stats": None,
            "base_effects": [
                {"type": "heal", "target": "all_allies", "value": 1, "condition": "on_turn_start"},
                {"type": "buff", "target": "all_allies", "value": 1, "subtype": "max_health", "condition": "on_turn_end"},
            ],
            "lore_template": "传说中的生命之泉，泉水所到之处生机盎然。",
            "tags": ["heal", "buff", "relic", "passive"],
        },
        # BLACK_GOLD
        {
            "archetype_id": "HEALTH_BLACK_GOLD_MESSIAH",
            "faction": "HEALTH",
            "rarity": "BLACK_GOLD",
            "card_type": "UNIT",
            "name_templates": ["救世{name}", "弥赛亚{name}", "圣子{name}"],
            "base_cost": 8,
            "base_stats": {"attack": 5, "health": 10},
            "base_effects": [
                {"type": "heal", "target": "all_allies", "value": 5, "condition": "on_summon"},
                {"type": "revive", "target": "all_allies", "value": 1, "condition": "faith_threshold_7"},
                {"type": "shield", "target": "all_allies", "value": 3, "condition": "on_turn_start"},
            ],
            "lore_template": "祂降临世间，带来终极的救赎与新生。",
            "tags": ["heal", "revive", "shield", "messiah", "ultimate"],
        },
    ],

    # ============================================================
    # LOVE 阵营 — 偷取、控制、重定向、链接
    # ============================================================
    "LOVE": [
        {
            "archetype_id": "LOVE_IRON_CHARMER",
            "faction": "LOVE",
            "rarity": "IRON",
            "card_type": "UNIT",
            "name_templates": ["魅惑{name}", "倾心{name}", "迷情{name}", "爱慕{name}", "花仙{name}", "甜心{name}", "蜜语{name}", "柔情{name}"],
            "base_cost": 2,
            "base_stats": {"attack": 2, "health": 3},
            "base_effects": [{"type": "steal", "target": "target_enemy", "value": 1, "subtype": "attack"}],
            "lore_template": "{name}以倾城之姿迷惑对手，削弱其力量。",
            "tags": ["steal", "control"],
        },
        {
            "archetype_id": "LOVE_IRON_REDIRECT",
            "faction": "LOVE",
            "rarity": "IRON",
            "card_type": "SPELL",
            "name_templates": ["移情", "镜花水月", "爱之陷阱", "错爱", "情网", "红尘迷障", "幻惑"],
            "base_cost": 1,
            "base_stats": None,
            "base_effects": [{"type": "redirect", "target": "target_enemy_attack", "value": 1}],
            "lore_template": "敌人的攻击被爱的力量扭转，指向错误的方向。",
            "tags": ["redirect", "control", "spell"],
        },
        {
            "archetype_id": "LOVE_IRON_BOND",
            "faction": "LOVE",
            "rarity": "IRON",
            "card_type": "UNIT",
            "name_templates": ["牵绊{name}", "心有灵犀{name}", "情缘{name}", "伴侣{name}", "知己{name}", "红颜{name}", "蓝颜{name}"],
            "base_cost": 2,
            "base_stats": {"attack": 1, "health": 4},
            "base_effects": [{"type": "link", "target": "target_ally", "value": 1}],
            "lore_template": "{name}与同伴心灵相连，共享彼此的力量。",
            "tags": ["link", "bond"],
        },
        {
            "archetype_id": "LOVE_IRON_HEART",
            "faction": "LOVE",
            "rarity": "IRON",
            "card_type": "ITEM",
            "name_templates": ["爱心吊坠", "定情戒指", "玫瑰胸针", "情人结", "恋之护符", "心形宝石", "温暖围巾"],
            "base_cost": 1,
            "base_stats": None,
            "base_effects": [{"type": "buff", "target": "linked_ally", "value": 1, "subtype": "all"}],
            "lore_template": "小小的信物承载着深沉的爱意，为牵挂之人带来力量。",
            "tags": ["link", "buff", "item"],
        },
        {
            "archetype_id": "LOVE_IRON_CONFUSE",
            "faction": "LOVE",
            "rarity": "IRON",
            "card_type": "SPELL",
            "name_templates": ["意乱情迷", "心神恍惚", "朦胧情愫", "神魂颠倒", "迷魂", "桃花劫", "情毒"],
            "base_cost": 2,
            "base_stats": None,
            "base_effects": [{"type": "debuff", "target": "target_enemy", "value": 2, "subtype": "attack"}],
            "lore_template": "爱的力量使敌人心神不宁，战斗力大幅下降。",
            "tags": ["debuff", "control", "spell"],
        },
        # BRONZE
        {
            "archetype_id": "LOVE_BRONZE_ENCHANTRESS",
            "faction": "LOVE",
            "rarity": "BRONZE",
            "card_type": "UNIT",
            "name_templates": ["妖姬{name}", "魅魔{name}", "爱神使者{name}", "情圣{name}", "花魁{name}", "倾城{name}"],
            "base_cost": 3,
            "base_stats": {"attack": 3, "health": 4},
            "base_effects": [
                {"type": "steal", "target": "target_enemy", "value": 2, "subtype": "attack", "condition": "on_summon"},
                {"type": "buff", "target": "self", "value": 1, "subtype": "attack", "condition": "on_steal"},
            ],
            "lore_template": "{name}的美貌令人窒息，她所夺取的一切都化为己用。",
            "tags": ["steal", "buff", "unit"],
        },
        {
            "archetype_id": "LOVE_BRONZE_FATE",
            "faction": "LOVE",
            "rarity": "BRONZE",
            "card_type": "SPELL",
            "name_templates": ["命运之线", "爱之枷锁", "情人怨", "风月无边", "情天恨海", "比翼连理"],
            "base_cost": 3,
            "base_stats": None,
            "base_effects": [
                {"type": "control", "target": "target_enemy", "value": 1},
                {"type": "damage", "target": "controlled_enemy", "value": 2},
            ],
            "lore_template": "命运的红线将灵魂牵在一起，无法挣脱。",
            "tags": ["control", "damage", "spell"],
        },
        {
            "archetype_id": "LOVE_BRONZE_CUPID",
            "faction": "LOVE",
            "rarity": "BRONZE",
            "card_type": "RELIC",
            "name_templates": ["邱比特之弓", "爱神之箭", "姻缘红线", "情缘石", "和合符", "同心锁"],
            "base_cost": 4,
            "base_stats": None,
            "base_effects": [
                {"type": "link", "target": "any_two", "value": 1, "condition": "on_summon"},
                {"type": "heal", "target": "linked", "value": 2, "condition": "on_turn_start"},
            ],
            "lore_template": "爱神之箭将两人的命运连在一起，共渡难关。",
            "tags": ["link", "heal", "relic"],
        },
        # SILVER
        {
            "archetype_id": "LOVE_SILVER_SIREN",
            "faction": "LOVE",
            "rarity": "SILVER",
            "card_type": "UNIT",
            "name_templates": ["海妖{name}", "塞壬{name}", "美人鱼{name}", "洛神{name}"],
            "base_cost": 4,
            "base_stats": {"attack": 3, "health": 5},
            "base_effects": [
                {"type": "control", "target": "all_enemies", "value": 1, "condition": "on_summon"},
                {"type": "steal", "target": "controlled_enemy", "value": 1, "subtype": "health", "condition": "on_turn_start"},
            ],
            "lore_template": "{name}的歌声让所有人沉醉，失去抵抗的同时生命力也被汲取。",
            "tags": ["control", "steal", "aoe"],
        },
        {
            "archetype_id": "LOVE_SILVER_SOULMATE",
            "faction": "LOVE",
            "rarity": "SILVER",
            "card_type": "SPELL",
            "name_templates": ["灵魂伴侣", "永结同心", "天作之合", "生死相许"],
            "base_cost": 3,
            "base_stats": None,
            "base_effects": [
                {"type": "link", "target": "all_allies", "value": 1},
                {"type": "buff", "target": "linked", "value": 2, "subtype": "all"},
            ],
            "lore_template": "至高的羁绊将全队灵魂相连，力量倍增。",
            "tags": ["link", "buff", "aoe"],
        },
        # GOLD
        {
            "archetype_id": "LOVE_GOLD_APHRODITE",
            "faction": "LOVE",
            "rarity": "GOLD",
            "card_type": "UNIT",
            "name_templates": ["爱神{name}", "维纳斯{name}", "阿芙洛{name}"],
            "base_cost": 6,
            "base_stats": {"attack": 5, "health": 6},
            "base_effects": [
                {"type": "steal", "target": "all_enemies", "value": 2, "subtype": "attack", "condition": "on_summon"},
                {"type": "control", "target": "target_enemy", "value": 1, "condition": "on_turn_start"},
                {"type": "buff", "target": "all_allies", "value": 2, "subtype": "attack", "condition": "on_steal"},
            ],
            "lore_template": "爱之女神降临，万物俯首，敌人之力尽归己方。",
            "tags": ["steal", "control", "buff", "goddess"],
        },
        {
            "archetype_id": "LOVE_GOLD_ETERNAL",
            "faction": "LOVE",
            "rarity": "GOLD",
            "card_type": "RELIC",
            "name_templates": ["永恒之爱", "不灭之心", "至死不渝"],
            "base_cost": 5,
            "base_stats": None,
            "base_effects": [
                {"type": "link", "target": "all_allies", "value": 1, "condition": "on_summon"},
                {"type": "redirect", "target": "all_enemy_attacks", "value": 1, "condition": "on_linked"},
            ],
            "lore_template": "永恒的爱之誓言，任何伤害都会被分享和消解。",
            "tags": ["link", "redirect", "relic", "defense"],
        },
        # BLACK_GOLD
        {
            "archetype_id": "LOVE_BLACK_GOLD_EROS",
            "faction": "LOVE",
            "rarity": "BLACK_GOLD",
            "card_type": "UNIT",
            "name_templates": ["原初爱神{name}", "厄洛斯{name}", "至高之爱{name}"],
            "base_cost": 7,
            "base_stats": {"attack": 4, "health": 8},
            "base_effects": [
                {"type": "control", "target": "all_enemies", "value": 1, "condition": "on_summon"},
                {"type": "steal", "target": "all_enemies", "value": 3, "subtype": "all", "condition": "on_turn_start"},
                {"type": "link", "target": "all", "value": 1, "condition": "on_summon"},
            ],
            "lore_template": "原初的爱之力量，世间万物皆在爱的法则下运行。",
            "tags": ["control", "steal", "link", "ultimate"],
        },
    ],

    # ============================================================
    # CAREER 阵营 — 连击、成长、力量增幅
    # ============================================================
    "CAREER": [
        {
            "archetype_id": "CAREER_IRON_GRUNT",
            "faction": "CAREER",
            "rarity": "IRON",
            "card_type": "UNIT",
            "name_templates": ["勤勉{name}", "奋斗者{name}", "实干家{name}", "努力{name}", "拼搏{name}", "工匠{name}", "学徒{name}", "新人{name}"],
            "base_cost": 1,
            "base_stats": {"attack": 2, "health": 2},
            "base_effects": [{"type": "buff", "target": "self", "value": 1, "subtype": "attack", "condition": "on_attack"}],
            "lore_template": "{name}相信每一次努力都在积累未来的力量。",
            "tags": ["buff", "scaling", "combo"],
        },
        {
            "archetype_id": "CAREER_IRON_TRAINEE",
            "faction": "CAREER",
            "rarity": "IRON",
            "card_type": "UNIT",
            "name_templates": ["实习生{name}", "新人{name}", "练习{name}", "积累{name}", "成长{name}", "菜鸟{name}", "新人王{name}"],
            "base_cost": 2,
            "base_stats": {"attack": 1, "health": 3},
            "base_effects": [{"type": "scaling", "target": "self", "value": 1, "subtype": "attack", "condition": "on_turn_start", "max": 5}],
            "lore_template": "初入职场，{name}的潜力不可限量。",
            "tags": ["scaling", "growth"],
        },
        {
            "archetype_id": "CAREER_IRON_MOTIVATION",
            "faction": "CAREER",
            "rarity": "IRON",
            "card_type": "SPELL",
            "name_templates": ["激励", "鼓舞", "加油", "动员", "喝彩", "表彰", "嘉奖"],
            "base_cost": 1,
            "base_stats": None,
            "base_effects": [{"type": "buff", "target": "target_ally", "value": 2, "subtype": "attack"}],
            "lore_template": "一句真诚的鼓励，足以点燃奋斗的火焰。",
            "tags": ["buff", "spell"],
        },
        {
            "archetype_id": "CAREER_IRON_TOOL",
            "faction": "CAREER",
            "rarity": "IRON",
            "card_type": "ITEM",
            "name_templates": ["效率手册", "时间管理器", "工作台", "灵感笔记", "日程本", "生产力工具"],
            "base_cost": 1,
            "base_stats": None,
            "base_effects": [{"type": "buff", "target": "self", "value": 1, "subtype": "cost_reduction"}],
            "lore_template": "善用工具，事半功倍。",
            "tags": ["buff", "item", "utility"],
        },
        {
            "archetype_id": "CAREER_IRON_FOCUS",
            "faction": "CAREER",
            "rarity": "IRON",
            "card_type": "SPELL",
            "name_templates": ["专注", "心流", "入定", "沉浸", "聚精会神", "全神贯注", "一心一意"],
            "base_cost": 2,
            "base_stats": None,
            "base_effects": [{"type": "combo", "target": "self", "value": 1, "condition": "on_next_action"}],
            "lore_template": "专注的心流状态让每一次行动都更有效率。",
            "tags": ["combo", "spell"],
        },
        # BRONZE
        {
            "archetype_id": "CAREER_BRONZE_MANAGER",
            "faction": "CAREER",
            "rarity": "BRONZE",
            "card_type": "UNIT",
            "name_templates": ["经理{name}", "主管{name}", "总监{name}", "主任{name}", "领队{name}", "导师{name}"],
            "base_cost": 3,
            "base_stats": {"attack": 2, "health": 4},
            "base_effects": [
                {"type": "buff", "target": "all_allies", "value": 1, "subtype": "attack", "condition": "on_summon"},
                {"type": "combo", "target": "self", "value": 1, "condition": "on_ally_buffed"},
            ],
            "lore_template": "{name}以身作则，带领团队不断突破。",
            "tags": ["buff", "combo", "leader"],
        },
        {
            "archetype_id": "CAREER_BRONZE_DEADLINE",
            "faction": "CAREER",
            "rarity": "BRONZE",
            "card_type": "SPELL",
            "name_templates": ["截止日期", "冲刺", "赶工", "燃烧激情", "全力以赴", "最后一搏"],
            "base_cost": 2,
            "base_stats": None,
            "base_effects": [
                {"type": "buff", "target": "all_allies", "value": 3, "subtype": "attack"},
                {"type": "debuff", "target": "all_allies", "value": 1, "subtype": "health"},
            ],
            "lore_template": "Deadline 是第一生产力——燃烧生命换来爆发的效率。",
            "tags": ["buff", "debuff", "risk"],
        },
        {
            "archetype_id": "CAREER_BRONZE_NETWORK",
            "faction": "CAREER",
            "rarity": "BRONZE",
            "card_type": "RELIC",
            "name_templates": ["人脉网络", "商业名片", "合作备忘录", "联盟协议", "圈子通行证", "关系图"],
            "base_cost": 3,
            "base_stats": None,
            "base_effects": [
                {"type": "buff", "target": "all_allies", "value": 2, "subtype": "attack", "condition": "on_ally_summon"},
            ],
            "lore_template": "你的人脉就是你的力量，每一个新成员都让团队更强。",
            "tags": ["buff", "synergy", "relic"],
        },
        # SILVER
        {
            "archetype_id": "CAREER_SILVER_EXECUTIVE",
            "faction": "CAREER",
            "rarity": "SILVER",
            "card_type": "UNIT",
            "name_templates": ["副总裁{name}", "高管{name}", "决策者{name}", "战略家{name}"],
            "base_cost": 4,
            "base_stats": {"attack": 4, "health": 5},
            "base_effects": [
                {"type": "combo", "target": "self", "value": 2, "condition": "on_turn_end"},
                {"type": "scaling", "target": "self", "value": 1, "subtype": "attack", "condition": "on_combo_3"},
            ],
            "lore_template": "{name}熟稔商场之道，在连续决策中积累巨大的优势。",
            "tags": ["combo", "scaling", "executive"],
        },
        {
            "archetype_id": "CAREER_SILVER_PROMOTION",
            "faction": "CAREER",
            "rarity": "SILVER",
            "card_type": "SPELL",
            "name_templates": ["晋升", "破格提拔", "大放异彩", "一战成名"],
            "base_cost": 3,
            "base_stats": None,
            "base_effects": [
                {"type": "scaling", "target": "target_ally", "value": 2, "subtype": "attack"},
                {"type": "buff", "target": "target_ally", "value": 3, "subtype": "health"},
            ],
            "lore_template": "一次关键的晋升改变了一切——能力与责任并增。",
            "tags": ["scaling", "buff", "spell"],
        },
        # GOLD
        {
            "archetype_id": "CAREER_GOLD_CEO",
            "faction": "CAREER",
            "rarity": "GOLD",
            "card_type": "UNIT",
            "name_templates": ["总裁{name}", "创始人{name}", "企业家{name}"],
            "base_cost": 6,
            "base_stats": {"attack": 5, "health": 7},
            "base_effects": [
                {"type": "buff", "target": "all_allies", "value": 3, "subtype": "attack", "condition": "on_summon"},
                {"type": "combo", "target": "all_allies", "value": 1, "condition": "on_turn_end"},
                {"type": "scaling", "target": "self", "value": 1, "subtype": "all", "condition": "on_combo_5"},
            ],
            "lore_template": "伟大的企业从伟大的领导开始。{name}让所有人变得更好。",
            "tags": ["buff", "combo", "scaling", "leader", "legendary"],
        },
        {
            "archetype_id": "CAREER_GOLD_BLUEPRINT",
            "faction": "CAREER",
            "rarity": "GOLD",
            "card_type": "RELIC",
            "name_templates": ["商业蓝图", "战略版图", "宏图大业"],
            "base_cost": 3,
            "base_stats": None,
            "base_effects": [
                {"type": "combo", "target": "all_allies", "value": 1, "condition": "on_any_action"},
                {"type": "buff", "target": "all_allies", "value": 1, "subtype": "all", "condition": "on_combo_3"},
            ],
            "lore_template": "一纸蓝图画出了通往伟大的路径。",
            "tags": ["combo", "buff", "relic", "passive"],
        },
        # BLACK_GOLD
        {
            "archetype_id": "CAREER_BLACK_GOLD_LEGEND",
            "faction": "CAREER",
            "rarity": "BLACK_GOLD",
            "card_type": "UNIT",
            "name_templates": ["传奇{name}", "乔布斯{name}", "马斯克{name}"],
            "base_cost": 7,
            "base_stats": {"attack": 6, "health": 8},
            "base_effects": [
                {"type": "scaling", "target": "self", "value": 1, "subtype": "all", "condition": "on_turn_start", "max": 10},
                {"type": "combo", "target": "all_allies", "value": 2, "condition": "on_attack"},
                {"type": "buff", "target": "all_allies", "value": 5, "subtype": "attack", "condition": "on_scaling_max"},
            ],
            "lore_template": "改变世界的传奇人物。{name}存在的每一天都在重塑规则。",
            "tags": ["scaling", "combo", "buff", "legend", "ultimate"],
        },
    ],

    # ============================================================
    # FAMILY 阵营 — 召唤、血统（死亡触发）、协同
    # ============================================================
    "FAMILY": [
        {
            "archetype_id": "FAMILY_IRON_KIN",
            "faction": "FAMILY",
            "rarity": "IRON",
            "card_type": "UNIT",
            "name_templates": ["亲人{name}", "家人{name}", "血亲{name}", "手足{name}", "骨肉{name}", "至亲{name}", "同胞{name}", "宗亲{name}"],
            "base_cost": 2,
            "base_stats": {"attack": 2, "health": 3},
            "base_effects": [{"type": "buff", "target": "same_faction", "value": 1, "subtype": "attack", "condition": "on_summon"}],
            "lore_template": "血脉相连，{name}的到场让家人充满力量。",
            "tags": ["buff", "family", "synergy"],
        },
        {
            "archetype_id": "FAMILY_IRON_LEGACY",
            "faction": "FAMILY",
            "rarity": "IRON",
            "card_type": "SPELL",
            "name_templates": ["家训", "祖传秘方", "传家宝", "家规", "族谱", "祖先庇佑", "血脉召唤"],
            "base_cost": 1,
            "base_stats": None,
            "base_effects": [{"type": "summon", "target": "self", "value": 1, "subtype": "TOKEN_1_1"}],
            "lore_template": "家族的羁绊跨越时空，先祖之灵响应召唤。",
            "tags": ["summon", "spell"],
        },
        {
            "archetype_id": "FAMILY_IRON_GUARDIAN",
            "faction": "FAMILY",
            "rarity": "IRON",
            "card_type": "UNIT",
            "name_templates": ["守护者{name}", "家长{name}", "长辈{name}", "兄{name}", "姐{name}", "监护人{name}", "护卫{name}"],
            "base_cost": 3,
            "base_stats": {"attack": 1, "health": 5},
            "base_effects": [{"type": "shield", "target": "all_family", "value": 1, "condition": "on_turn_start"}],
            "lore_template": "{name}站在家人前面，用身躯撑起一片天。",
            "tags": ["shield", "family", "defense"],
        },
        {
            "archetype_id": "FAMILY_IRON_HEIRLOOM",
            "faction": "FAMILY",
            "rarity": "IRON",
            "card_type": "ITEM",
            "name_templates": ["家族戒指", "祖传项链", "怀表", "老照片", "家书", "族徽", "香火袋"],
            "base_cost": 1,
            "base_stats": None,
            "base_effects": [{"type": "buff", "target": "bearer", "value": 1, "subtype": "all", "condition": "on_family_death"}],
            "lore_template": "承载着家族记忆的宝物，逝者的力量会传递给生者。",
            "tags": ["buff", "item", "bloodline"],
        },
        {
            "archetype_id": "FAMILY_IRON_UNITY",
            "faction": "FAMILY",
            "rarity": "IRON",
            "card_type": "SPELL",
            "name_templates": ["团结", "家和万事兴", "齐心协力", "同舟共济", "合家欢", "其利断金"],
            "base_cost": 2,
            "base_stats": None,
            "base_effects": [{"type": "buff", "target": "all_family", "value": 2, "subtype": "attack"}],
            "lore_template": "家人同心，其利断金。",
            "tags": ["buff", "family", "spell"],
        },
        # BRONZE
        {
            "archetype_id": "FAMILY_BRONZE_ELDER",
            "faction": "FAMILY",
            "rarity": "BRONZE",
            "card_type": "UNIT",
            "name_templates": ["族长{name}", "奶奶{name}", "爷爷{name}", "长老{name}", "创始人{name}", "祖辈{name}"],
            "base_cost": 4,
            "base_stats": {"attack": 2, "health": 4},
            "base_effects": [
                {"type": "summon", "target": "self", "value": 2, "subtype": "TOKEN_1_1", "condition": "on_summon"},
                {"type": "buff", "target": "all_family", "value": 1, "subtype": "all", "condition": "on_death"},
            ],
            "lore_template": "{name}是家族的精神支柱，即便离世也将恩泽留给后人。",
            "tags": ["summon", "bloodline", "buff"],
        },
        {
            "archetype_id": "FAMILY_BRONZE_FEAST",
            "faction": "FAMILY",
            "rarity": "BRONZE",
            "card_type": "SPELL",
            "name_templates": ["团圆饭", "家族盛宴", "年夜饭", "合家团圆", "温馨晚餐", "节日聚餐"],
            "base_cost": 3,
            "base_stats": None,
            "base_effects": [
                {"type": "heal", "target": "all_family", "value": 3},
                {"type": "buff", "target": "all_family", "value": 1, "subtype": "health"},
            ],
            "lore_template": "围坐一桌的温馨时刻，治愈所有的疲惫与伤痛。",
            "tags": ["heal", "buff", "family", "spell"],
        },
        {
            "archetype_id": "FAMILY_BRONZE_ANCESTOR",
            "faction": "FAMILY",
            "rarity": "BRONZE",
            "card_type": "RELIC",
            "name_templates": ["祖先牌位", "祠堂", "家庙", "祖坟风水", "家族徽章", "族谱图"],
            "base_cost": 4,
            "base_stats": None,
            "base_effects": [
                {"type": "summon", "target": "self", "value": 1, "subtype": "TOKEN_2_2", "condition": "on_family_death"},
                {"type": "buff", "target": "summoned", "value": 1, "subtype": "all", "condition": "on_summon"},
            ],
            "lore_template": "祖先之灵守护着家族，每一次失去都带来新生。",
            "tags": ["summon", "bloodline", "relic"],
        },
        # SILVER
        {
            "archetype_id": "FAMILY_SILVER_MATRIARCH",
            "faction": "FAMILY",
            "rarity": "SILVER",
            "card_type": "UNIT",
            "name_templates": ["女族长{name}", "母亲{name}", "家庭支柱{name}", "家主{name}"],
            "base_cost": 5,
            "base_stats": {"attack": 3, "health": 6},
            "base_effects": [
                {"type": "summon", "target": "self", "value": 2, "subtype": "TOKEN_2_2", "condition": "on_turn_end"},
                {"type": "heal", "target": "all_family", "value": 2, "condition": "on_summon"},
            ],
            "lore_template": "{name}以无尽的爱滋养着家族的每一代。",
            "tags": ["summon", "heal", "family"],
        },
        {
            "archetype_id": "FAMILY_SILVER_REUNION",
            "faction": "FAMILY",
            "rarity": "SILVER",
            "card_type": "SPELL",
            "name_templates": ["家族大团圆", "世族聚会", "荣耀回归", "家族召唤"],
            "base_cost": 4,
            "base_stats": None,
            "base_effects": [
                {"type": "summon", "target": "self", "value": 3, "subtype": "TOKEN_1_1"},
                {"type": "buff", "target": "all_allies", "value": 1, "subtype": "attack", "condition": "on_summon"},
            ],
            "lore_template": "家族成员从四面八方赶来，力量在团聚中汇聚。",
            "tags": ["summon", "buff", "aoe", "spell"],
        },
        # GOLD
        {
            "archetype_id": "FAMILY_GOLD_DYNASTY",
            "faction": "FAMILY",
            "rarity": "GOLD",
            "card_type": "UNIT",
            "name_templates": ["王朝{name}", "世家{name}", "望族{name}"],
            "base_cost": 6,
            "base_stats": {"attack": 4, "health": 8},
            "base_effects": [
                {"type": "summon", "target": "self", "value": 2, "subtype": "TOKEN_3_3", "condition": "on_turn_start"},
                {"type": "buff", "target": "all_allies", "value": 2, "subtype": "all", "condition": "on_ally_summon"},
                {"type": "bloodline", "target": "all_family", "value": 2, "subtype": "attack", "condition": "on_death"},
            ],
            "lore_template": "传承百年的大世家，每一代都比上一代更强大。",
            "tags": ["summon", "buff", "bloodline", "dynasty"],
        },
        {
            "archetype_id": "FAMILY_GOLD_HEARTH",
            "faction": "FAMILY",
            "rarity": "GOLD",
            "card_type": "RELIC",
            "name_templates": ["永恒炉火", "家族之心", "不灭壁炉"],
            "base_cost": 4,
            "base_stats": None,
            "base_effects": [
                {"type": "heal", "target": "all_family", "value": 3, "condition": "on_turn_start"},
                {"type": "shield", "target": "all_family", "value": 2, "condition": "on_turn_end"},
            ],
            "lore_template": "永不熄灭的炉火，象征家族的温暖与坚固。",
            "tags": ["heal", "shield", "relic", "passive"],
        },
        # BLACK_GOLD
        {
            "archetype_id": "FAMILY_BLACK_GOLD_PATRIARCH",
            "faction": "FAMILY",
            "rarity": "BLACK_GOLD",
            "card_type": "UNIT",
            "name_templates": ["始祖{name}", "开基祖先{name}", "万世之宗{name}"],
            "base_cost": 8,
            "base_stats": {"attack": 5, "health": 10},
            "base_effects": [
                {"type": "summon", "target": "self", "value": 4, "subtype": "TOKEN_3_3", "condition": "on_summon"},
                {"type": "bloodline", "target": "all_allies", "value": 3, "subtype": "all", "condition": "on_death_any"},
                {"type": "buff", "target": "all_allies", "value": 2, "subtype": "all", "condition": "on_turn_start"},
            ],
            "lore_template": "家族的源头，万世根基。{name}的存在本身就是神话。",
            "tags": ["summon", "bloodline", "buff", "ultimate"],
        },
    ],

    # ============================================================
    # WEALTH 阵营 — 资源生成、风险回报、金币倍增
    # ============================================================
    "WEALTH": [
        {
            "archetype_id": "WEALTH_IRON_TRADER",
            "faction": "WEALTH",
            "rarity": "IRON",
            "card_type": "UNIT",
            "name_templates": ["商人{name}", "掌柜{name}", "买卖{name}", "贩子{name}", "金主{name}", "富翁{name}", "财主{name}", "老板{name}"],
            "base_cost": 2,
            "base_stats": {"attack": 1, "health": 3},
            "base_effects": [{"type": "resource_gen", "target": "self", "value": 1, "subtype": "gold"}],
            "lore_template": "{name}深谙生财之道，钱能生钱。",
            "tags": ["resource_gen", "gold"],
        },
        {
            "archetype_id": "WEALTH_IRON_GAMBLE",
            "faction": "WEALTH",
            "rarity": "IRON",
            "card_type": "SPELL",
            "name_templates": ["孤注一掷", "以小博大", "风险投资", "豪赌", "一搏", "押注", "梭哈"],
            "base_cost": 1,
            "base_stats": None,
            "base_effects": [{"type": "risk_reward", "target": "self", "value": 4, "risk": 2}],
            "lore_template": "高风险高回报——要么一夜暴富，要么血本无归。",
            "tags": ["risk_reward", "spell"],
        },
        {
            "archetype_id": "WEALTH_IRON_COIN",
            "faction": "WEALTH",
            "rarity": "IRON",
            "card_type": "UNIT",
            "name_templates": ["金币{name}", "元宝{name}", "财神{name}", "招财{name}", "进宝{name}", "金蟾{name}", "貔貅{name}"],
            "base_cost": 1,
            "base_stats": {"attack": 1, "health": 1},
            "base_effects": [{"type": "resource_gen", "target": "self", "value": 2, "subtype": "gold", "condition": "on_death"}],
            "lore_template": "{name}虽小，但离去时也能带来意外的收获。",
            "tags": ["resource_gen", "death_trigger"],
        },
        {
            "archetype_id": "WEALTH_IRON_CHEST",
            "faction": "WEALTH",
            "rarity": "IRON",
            "card_type": "ITEM",
            "name_templates": ["存钱罐", "宝箱", "金库钥匙", "账本", "保险柜", "锦囊", "钱袋"],
            "base_cost": 1,
            "base_stats": None,
            "base_effects": [{"type": "resource_gen", "target": "self", "value": 1, "subtype": "gold", "condition": "on_turn_start"}],
            "lore_template": "积少成多，涓涓细流汇成江海。",
            "tags": ["resource_gen", "item", "passive"],
        },
        {
            "archetype_id": "WEALTH_IRON_BARGAIN",
            "faction": "WEALTH",
            "rarity": "IRON",
            "card_type": "SPELL",
            "name_templates": ["讨价还价", "打折", "促销", "优惠", "砍价", "清仓甩卖", "跳楼价"],
            "base_cost": 0,
            "base_stats": None,
            "base_effects": [{"type": "cost_reduce", "target": "next_card", "value": 1}],
            "lore_template": "精明的商人从不多花一分冤枉钱。",
            "tags": ["cost_reduce", "spell", "utility"],
        },
        # BRONZE
        {
            "archetype_id": "WEALTH_BRONZE_INVESTOR",
            "faction": "WEALTH",
            "rarity": "BRONZE",
            "card_type": "UNIT",
            "name_templates": ["投资家{name}", "资本家{name}", "银行家{name}", "理财师{name}", "金融{name}", "操盘手{name}"],
            "base_cost": 3,
            "base_stats": {"attack": 2, "health": 4},
            "base_effects": [
                {"type": "resource_gen", "target": "self", "value": 1, "subtype": "gold", "condition": "on_turn_start"},
                {"type": "gold_multiply", "target": "self", "value": 2, "condition": "on_gold_5"},
            ],
            "lore_template": "{name}的眼光独到，投资回报如滚雪球般增长。",
            "tags": ["resource_gen", "multiply", "invest"],
        },
        {
            "archetype_id": "WEALTH_BRONZE_LOAN",
            "faction": "WEALTH",
            "rarity": "BRONZE",
            "card_type": "SPELL",
            "name_templates": ["借贷", "融资", "杠杆", "信用贷款", "过桥资金", "天使投资"],
            "base_cost": 0,
            "base_stats": None,
            "base_effects": [
                {"type": "resource_gen", "target": "self", "value": 5, "subtype": "gold"},
                {"type": "debuff", "target": "self", "value": 2, "subtype": "gold_per_turn"},
            ],
            "lore_template": "借来的钱总要还，但在那之前可以大干一场。",
            "tags": ["resource_gen", "risk", "spell"],
        },
        {
            "archetype_id": "WEALTH_BRONZE_MERCHANT",
            "faction": "WEALTH",
            "rarity": "BRONZE",
            "card_type": "RELIC",
            "name_templates": ["商会令", "营业执照", "特许经营证", "商业契约", "合伙协议", "商业秘密"],
            "base_cost": 3,
            "base_stats": None,
            "base_effects": [
                {"type": "resource_gen", "target": "self", "value": 1, "subtype": "gold", "condition": "on_any_card_played"},
                {"type": "gold_multiply", "target": "self", "value": 2, "condition": "on_turn_5"},
            ],
            "lore_template": "合法的商业权力带来的收益是持久的。",
            "tags": ["resource_gen", "multiply", "relic"],
        },
        # SILVER
        {
            "archetype_id": "WEALTH_SILVER_MAGNATE",
            "faction": "WEALTH",
            "rarity": "SILVER",
            "card_type": "UNIT",
            "name_templates": ["巨富{name}", "财阀{name}", "商业巨头{name}", "寡头{name}"],
            "base_cost": 5,
            "base_stats": {"attack": 3, "health": 5},
            "base_effects": [
                {"type": "gold_multiply", "target": "self", "value": 2, "condition": "on_turn_start"},
                {"type": "buff", "target": "all_allies", "value": 1, "subtype": "attack", "condition": "on_gold_10"},
            ],
            "lore_template": "{name}的财富帝国如同滚雪球般壮大，富可敌国。",
            "tags": ["multiply", "buff", "wealth"],
        },
        {
            "archetype_id": "WEALTH_SILVER_JACKPOT",
            "faction": "WEALTH",
            "rarity": "SILVER",
            "card_type": "SPELL",
            "name_templates": ["中头奖", "天降横财", "一夜暴富", "彩票大奖"],
            "base_cost": 2,
            "base_stats": None,
            "base_effects": [
                {"type": "risk_reward", "target": "self", "value": 10, "risk": 5},
                {"type": "gold_multiply", "target": "self", "value": 3, "condition": "on_success"},
            ],
            "lore_template": "命运的轮盘转动——要么倾家荡产，要么一夜暴富！",
            "tags": ["risk_reward", "multiply", "spell"],
        },
        # GOLD
        {
            "archetype_id": "WEALTH_GOLD_MIDAS",
            "faction": "WEALTH",
            "rarity": "GOLD",
            "card_type": "UNIT",
            "name_templates": ["点金手{name}", "迈达斯{name}", "炼金大师{name}"],
            "base_cost": 6,
            "base_stats": {"attack": 4, "health": 6},
            "base_effects": [
                {"type": "gold_multiply", "target": "self", "value": 3, "condition": "on_turn_end"},
                {"type": "resource_gen", "target": "self", "value": 3, "subtype": "gold", "condition": "on_summon"},
                {"type": "buff", "target": "all_allies", "value": 1, "subtype": "all", "condition": "on_gold_20"},
            ],
            "lore_template": "传说中触摸的一切都化为黄金。{name}的存在就是财富本身。",
            "tags": ["multiply", "resource_gen", "buff", "legendary"],
        },
        {
            "archetype_id": "WEALTH_GOLD_FORTUNE",
            "faction": "WEALTH",
            "rarity": "GOLD",
            "card_type": "RELIC",
            "name_templates": ["命运之轮", "幸运金币", "许愿宝石"],
            "base_cost": 4,
            "base_stats": None,
            "base_effects": [
                {"type": "risk_reward", "target": "self", "value": 8, "risk": 1, "condition": "on_turn_start"},
                {"type": "gold_multiply", "target": "self", "value": 2, "condition": "on_success"},
            ],
            "lore_template": "幸运女神眷顾持有者——风险几乎为零的财富盛宴。",
            "tags": ["risk_reward", "multiply", "relic", "lucky"],
        },
        # BLACK_GOLD
        {
            "archetype_id": "WEALTH_BLACK_GOLD_CROESUS",
            "faction": "WEALTH",
            "rarity": "BLACK_GOLD",
            "card_type": "UNIT",
            "name_templates": ["财富之神{name}", "无尽财富{name}", "至宝{name}"],
            "base_cost": 8,
            "base_stats": {"attack": 6, "health": 8},
            "base_effects": [
                {"type": "resource_gen", "target": "self", "value": 5, "subtype": "gold", "condition": "on_turn_start"},
                {"type": "gold_multiply", "target": "all_allies", "value": 2, "condition": "on_turn_end"},
                {"type": "buff", "target": "all_allies", "value": 2, "subtype": "all", "condition": "on_gold_30"},
            ],
            "lore_template": "财富之神，其金库深不见底，其慷慨泽被所有追随者。",
            "tags": ["resource_gen", "multiply", "buff", "ultimate"],
        },
    ],
}

# 稀有度配置
RARITY_CONFIG = {
    "IRON": {"name": "赤铁", "rate": 0.50, "per_faction": 37, "energy_level": 1, "multiplier": 1.0},
    "BRONZE": {"name": "青铜", "rate": 0.25, "per_faction": 18, "energy_level": 2, "multiplier": 1.3},
    "SILVER": {"name": "白银", "rate": 0.12, "per_faction": 9, "energy_level": 3, "multiplier": 1.7},
    "GOLD": {"name": "黄金", "rate": 0.10, "per_faction": 6, "energy_level": 4, "multiplier": 2.2},
    "BLACK_GOLD": {"name": "黑金", "rate": 0.03, "per_faction": 3, "energy_level": 5, "multiplier": 3.0},
}

# 保底配置
PITY_CONFIG = {
    "gold_pity": 30,  # 30抽保底GOLD
    "black_gold_pity": 100,  # 100抽保底BLACK_GOLD
}

# 阵营克制关系 (攻击方 → 被攻击方 → 倍率)
COUNTER_MAP = {
    "HEALTH": {"WEALTH": 1.5, "LOVE": 0.75},
    "WEALTH": {"FAMILY": 1.5, "HEALTH": 0.75},
    "FAMILY": {"LOVE": 1.5, "WEALTH": 0.75},
    "LOVE": {"CAREER": 1.5, "FAMILY": 0.75},
    "CAREER": {"HEALTH": 1.5, "LOVE": 0.75},
}

# 卡牌类型名称
CARD_TYPE_NAMES_V060 = {
    "UNIT": "单位",
    "SPELL": "法术",
    "ITEM": "装备",
    "RELIC": "遗物",
}

# 稀有度名称
RARITY_NAMES = {k: v["name"] for k, v in RARITY_CONFIG.items()}
